spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/dataflowdb?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin666
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      connection-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        
        generate_statistics: true
        format-sql: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            missing_cache_strategy: create
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  devtools:
    restart:
      enabled: false
  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms  ##connection timeout
    jedis: ##default use lettuce,we not use
      pool:
        max-active: 100
        max-idle: 8
        min-idle: 2
        max-wait: 30000ms

    